(()=>{
 const stage=document.getElementById('stage');if(!stage)return;
 const nav=document.createElement('nav');nav.id='portfolio-nav';nav.inert=true;nav.setAttribute('aria-label','Main navigation');nav.innerHTML='<a href="#projects">Projects</a><a href="about.html?v=phone-3">About</a><a href="contact.html?v=phone-3">Contact</a>';stage.append(nav);
 const jump=document.createElement('a');jump.id='projects-down';jump.hidden=true;jump.href='#projects';jump.textContent='Explore projects ↓';stage.append(jump);
 const hive=document.createElement('button');hive.id='hive-egg';hive.setAttribute('aria-label','Beehive');hive.hidden=true;stage.append(hive);
 const chair=document.createElement('a');chair.id='chair-about';chair.href='about.html?v=phone-3';chair.setAttribute('aria-label','About Tejas');chair.hidden=true;stage.append(chair);
 const canvas=document.createElement('canvas');canvas.id='bee-swarm';canvas.setAttribute('aria-hidden','true');canvas.hidden=true;stage.append(canvas);const ctx=canvas.getContext('2d'),sheet=new Image();let promise=null,running=false,origin={x:0,y:0};
 function load(){if(!promise){sheet.src='viewer-assets/bee-sprites.webp';promise=sheet.decode().catch(()=>{promise=null;});}return promise;}
 function hotspots(){const w=stage.clientWidth,h=stage.clientHeight,s=Math.max(w,h),left=w<=650?0:(w-s)/2,top=(h-s)/2;origin={x:left+s*.075,y:top+s*.385};for(const [el,x,y,sw,sh] of [[hive,.036,.34,.09,.105],[chair,.023,.52,.19,.13]]){el.style.left=(left+x*s)+'px';el.style.top=(top+y*s)+'px';el.style.width=sw*s+'px';el.style.height=sh*s+'px';}}
 window.updatePortfolioLinks=(p,mode)=>{const home=mode==='gallery'&&p<.275;const revealed=p>=.245;nav.classList.toggle('revealed',revealed);nav.inert=!revealed;stage.classList.toggle('intro-complete',revealed);nav.classList.toggle('on-white',p>.31);hive.hidden=chair.hidden=!(home&&p>=.23);jump.hidden=!(home&&revealed);if(home&&p>=.23){hotspots();load();}};
 for(const a of [jump,nav.querySelector('[href="#projects"]')])a.addEventListener('click',()=>window.dispatchEvent(new Event('portfolio:projects')));window.addEventListener('resize',hotspots);hotspots();
 hive.onclick=async()=>{if(running)return;running=true;await load();if(!sheet.naturalWidth){running=false;return;}const W=stage.clientWidth,H=stage.clientHeight;canvas.width=W;canvas.height=H;canvas.hidden=false;const count=W<650?65:110,bees=Array.from({length:count},(_,i)=>({x:Math.random()*W,y:Math.random()*H,phase:Math.random()*6.28,delay:Math.random()*.3,size:55+Math.random()*105,angle:i%8,side:i%2?1:-1})),start=performance.now();
 function frame(now){const t=(now-start)/1000;ctx.clearRect(0,0,W,H);if(t>=3.8||document.hidden){canvas.hidden=true;running=false;return;}for(const b of bees){const u=t-b.delay;if(u<0)continue;const p=Math.min(1,u/1.1),e=1-(1-p)**3;let x=origin.x+(b.x-origin.x)*e+Math.sin(u*7+b.phase)*18*e,y=origin.y+(b.y-origin.y)*e+Math.cos(u*6+b.phase)*15*e,s=b.size*(.12+.88*e),alpha=1;if(t>2.35){const v=Math.min(1,(t-2.35)/1.4);x+=b.side*(W+200)*v*v;y-=(H+200)*v*v;s*=1-v*.6;alpha=1-v*v;}const angle=(b.angle+Math.floor(u*1.6))%8,f=Math.floor((u+b.phase)*16)%8;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(u*4+b.phase)*.35);ctx.globalAlpha=alpha;ctx.drawImage(sheet,angle*192,f*192,192,192,-s/2,-s/2,s,s);ctx.restore();}requestAnimationFrame(frame);}requestAnimationFrame(frame);};
})();

